# ------------------------------------------------------------------------------
# docker build -t pykalman --no-cache -f Dockerfile.pykalman .
# docker run -it --rm --name pykalman -v `pwd`:/app/ pykalman
# ------------------------------------------------------------------------------
FROM python:3.13.7-slim-bookworm
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# Update and cleanup
RUN apt-get update \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

# Install PyKalman
RUN pip3 install \
    easydict \
    ipython \
    matplotlib \
    openpyxl \
    pandas \
    pykalman \
    pyyaml

WORKDIR /app

CMD ["/bin/bash"]
