# ------------------------------------------------------------------------------
# docker build -t llm --no-cache -f Dockerfile.llm .
# docker run -it --rm --gpus all --name llm -v `pwd`:/app/ llm
# ------------------------------------------------------------------------------
ARG CUDA_VER=12.3.2
FROM nvidia/cuda:${CUDA_VER}-cudnn9-runtime-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# General dependencies and Python
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    # python3
    python3 \
    python3-pip \
    python3-setuptools \
    python3-dev \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

# Install PyTorch
RUN pip3 install \
    accelerate \
    easydict \
    datasets \
    ipython \
    matplotlib \
    openpyxl \
    pandas \
    pyyaml \
    scipy \
    torch \
    torchvision \
    torchaudio \
    transformers

WORKDIR /app
