# ------------------------------------------------------------------------------
# docker build -t prophet --no-cache -f Dockerfile.prophet .
# docker run -it --rm --name prophet -v `pwd`:/app/ prophet
# ------------------------------------------------------------------------------
FROM python:3.13.7-slim-bookworm
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# Update and cleanup
RUN apt-get update \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

# Install Prophet
RUN pip3 install \
    easydict \
    ipython \
    openpyxl \
    prophet==1.1.7 \
    plotly \
    pyyaml \
    scipy

WORKDIR /app

CMD ["/bin/bash"]
