# ------------------------------------------------------------------------------
# docker build -t gpy --no-cache -f Dockerfile.gpy .
# docker run -it --rm --name gpy -v `pwd`:/app/ gpy
# ------------------------------------------------------------------------------
FROM python:3.12.11-slim-bookworm
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# General dependencies and Python
RUN apt-get update \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

# Install GPy
RUN pip3 install \
    easydict \
    ipython \
    gpy \
    matplotlib \
    openpyxl \
    pandas \
    pyyaml \
    scipy

WORKDIR /app

CMD ["/bin/bash"]
