# ------------------------------------------------------------------------------
# docker build -t pydata --no-cache -f Dockerfile.pydata .
# docker run -it --rm --name pydata -v `pwd`:/app/ pydata
# ------------------------------------------------------------------------------
FROM python:3.9.21-slim
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# General dependencies and Python
RUN apt-get update \
    && apt-get upgrade -y \
    # && apt-get install -y --no-install-recommends \
    # python3 \
    # python3-pip \
    # python3-setuptools \
    # python3-dev \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

# Install libraries
RUN pip3 install \
    easydict \
    ipython \
    matplotlib \
    openpyxl \
    pandas \
    requests \
    scikit-learn \
    scipy

WORKDIR /app

CMD ["/bin/bash"]
